## 期约与异步函数
对象状态不受外界影响，主要有三种状态：进行中pending、已成功fulfilled、已失败rejected  
一旦状态改变、就不会再变  
优点：异步操作以同步操作的流程表达出来，避免层层嵌套Promise对象提供统一的接口，使得控制异步操作更加容易
缺点：无法取消Promise如果不设置回调函数，Promise内部抛出的错误，不会反应到外部当处于pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）  
**某些事件不断地反复发生，一般来说，使用 Stream ？？ 模式是比部署Promise更好的选择**


1.promise是一个构造函数 需要使用new Promise() 进行构造Promise实例  
2.Promise构造函数接收一个函数作为参数，该函数的两个参数分别是 resolve reject 这两个是函数由js引擎提供  
  -resolve函数的作用是将promise对象的状态从pending-resolved 在异步成功是调用将参数传递出去  
  -reject函数的作用是将promis对象的状态从ending-rejected 异步操作失败时调用将报错信息传递出去  
3.Promise 实例生成后可以使用then方法分别指定resolved和rejected状态的回调函数  都接受Promise对象传出的值作为参数
```js
const promise = new Promise(function(resolve, reject) {
  // ... some code
  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});

promise.then(function(value) {
  // success  Promise对象的状态变为resolved时调用
}, function(error) {
  // failure  Promise对象的状态变为rejected时调
}); 

function timeout(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(resolve, ms, 'done');
  });
}
timeout(100).then((value) => {
  console.log(value);
});

const p1 = new Promise(function (resolve, reject) {
  setTimeout(() => reject(new Error('fail')), 3000)
})
const p2 = new Promise(function (resolve, reject) {
  setTimeout(() => resolve(p1), 1000)
})
p2
  .then(result => console.log(result))
  .catch(error => console.log(error))
```
### then
1.Promise 实例具有then方法，也就是说，then方法是定义在原型对象  
2.它的作用是为 Promise 实例添加状态改变时的回调函数。前面说过，then方法的第一个参数是resolved状态的回调函数，第二个参数是rejected状态的回调函数，它们都是可选的
```js
getJSON("/post/1.json").then(
  post => getJSON(post.commentURL)
).then(
  comments => console.log("resolved: ", comments),
  err => console.log("rejected: ", err)
);
// then 的链式调用 返回的是 新的promise对象
```
## catch
用于添加拒绝处理程序 是一个语法糖
```js
1.then(null, rejection)或.then(undefined, rejection)的别名，用于指定发生错误时的回调函数。
2.可以发现reject()方法的作用，等同于抛出错误。
3.Promise 状态已经变成resolved，再抛出错误是无效的
4.Promise 对象的错误具有‘冒泡’属性，会一直向后传递，直到被捕获为止
5.第二个catch()方法用来捕获前一个catch()方法抛出的错误
6.不要在then()方法里面定义 Reject 状态的回调函数（即then的第二个参数），总是使用catch方法。
7.一般总是建议，Promise 对象后面要跟catch()方法，这样可以处理 Promise 内部发生的错误。catch()方法返回的还是一个 Promise 对象，因此后面还可以接着调用then()方法
```